name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3 - Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4 - Build static site
      - name: Export Jinja2 templates
        run: |
          mkdir build
          python render.py  # your script to render Jinja2 → ./build

      # Step 5 - Save build for deploy
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: build

      # Step 6 - Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
